version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  registration:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres:postgres  
